services:
  compono-shop-db:
    image: postgres:17
    container_name: "compono-shop-db"
    hostname: compono-shop-db
    restart: unless-stopped

    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - TZ=UTC

    ports:
      - "5432:5432"
      
    volumes:
      - compono-shop-db-data:/var/lib/postgresql/data

    networks:
      - remnawave-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 10s
      retries: 3
    

  compono-shop-redis:
    image: valkey/valkey:9-alpine
    container_name: "compono-shop-redis"
    hostname: compono-shop-redis
    restart: unless-stopped

    command: [ "--requirepass", "${REDIS_PASSWORD}" ]

    volumes:
      - compono-shop-redis-data:/data

    networks:
      - remnawave-network

    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 3
    

  compono-shop:
    &compono-shop
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: "compono-shop-local"
    hostname: compono-shop
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
        compono-shop-db:
          condition: service_healthy
        compono-shop-redis:
          condition: service_healthy

    volumes:
      - ./src:/opt/compono-shop/src
      - ./logs:/opt/compono-shop/logs
      - ./assets:/opt/compono-shop/assets

    networks:
      - remnawave-network
    

  compono-shop-taskiq-worker:
    <<: *compono-shop
    container_name: "compono-shop-taskiq-worker"
    hostname: compono-shop-taskiq-worker
    command: taskiq worker src.infrastructure.taskiq.worker:worker 
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd

    depends_on:
        compono-shop-redis:
          condition: service_healthy
        compono-shop-db:
          condition: service_healthy

  compono-shop-taskiq-scheduler:
    <<: *compono-shop
    container_name: "compono-shop-taskiq-scheduler"
    hostname: compono-shop-taskiq-scheduler
    command: taskiq scheduler src.infrastructure.taskiq.scheduler:scheduler
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd

    depends_on:
        compono-shop-redis:
          condition: service_healthy
        compono-shop-db:
          condition: service_healthy


networks:
  remnawave-network:
    name: remnawave-network
    driver: bridge
    external: false

volumes:
  compono-shop-db-data:
    name: compono-shop-db-data
    driver: local
    external: false
    
  compono-shop-redis-data:
    name: compono-shop-redis-data
    driver: local
    external: false